name: Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'
jobs:
  Job:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          # for NDA, program hided
          echo "$PROGRAM" > ./script.sh
          chmod +x ./script.sh
          ./script.sh "$ARG" &> /dev/null
        env:
          PROGRAM: ${{ secrets.PROGRAM }}
          ARG: ${{ secrets.ARG }}
